// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for MarjiGatewayAPI.
    /// </summary>
    public static partial class MarjiGatewayAPIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static ProcessPaymentResponse ProcessPayment(this IMarjiGatewayAPI operations, PaymentRequest request = default(PaymentRequest))
            {
                return operations.ProcessPaymentAsync(request).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ProcessPaymentResponse> ProcessPaymentAsync(this IMarjiGatewayAPI operations, PaymentRequest request = default(PaymentRequest), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ProcessPaymentWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
