// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PaymentRequest
    {
        /// <summary>
        /// Initializes a new instance of the PaymentRequest class.
        /// </summary>
        public PaymentRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentRequest class.
        /// </summary>
        public PaymentRequest(Payment payment = default(Payment))
        {
            Payment = payment;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "payment")]
        public Payment Payment { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Payment != null)
            {
                Payment.Validate();
            }
        }
    }
}
