// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProcessPaymentResponse
    {
        /// <summary>
        /// Initializes a new instance of the ProcessPaymentResponse class.
        /// </summary>
        public ProcessPaymentResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProcessPaymentResponse class.
        /// </summary>
        public ProcessPaymentResponse(bool? isSuccess = default(bool?), string identifier = default(string))
        {
            IsSuccess = isSuccess;
            Identifier = identifier;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isSuccess")]
        public bool? IsSuccess { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "identifier")]
        public string Identifier { get; set; }

    }
}
